name: dasarata_mobile
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  envied: ^0.5.4+1
  get: ^4.6.6
  logger: ^2.4.0
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  cached_network_image: ^3.4.1
  google_nav_bar: ^5.0.6
  flutter_svg: ^2.0.10+1
  line_icons: ^2.0.3
  device_preview_minus: ^1.0.8
  dynamic_height_grid_view: ^0.0.4
  loading_animation_widget: ^1.3.0
  intl: ^0.19.0
  lottie: ^3.1.2
  animated_text_kit: ^4.2.2
  url_launcher: ^6.3.1
  location: ^6.0.2
  animated_snack_bar: ^0.4.0
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  toggle_switch: ^2.3.0
  label_marker: ^1.0.1
  dropdown_button2: ^2.3.9
  lazy_load_scrollview: ^1.3.0
  custom_accordion: ^1.0.0
  photo_view: ^0.15.0
  easy_stepper: ^0.8.5+1
  flutter_map_math: ^0.1.7
  file_picker: ^8.1.3
  image_picker: ^1.1.2
  flutter_localizations:
    sdk: flutter
  syncfusion_flutter_charts: ^27.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
  assets:
    - assets/icons/dashboard.svg
    - assets/icons/prospect.svg
    - assets/icons/chevron-right.svg
    - assets/icons/closing.svg
    - assets/icons/arrow-back.svg
    - assets/icons/current-location.svg
    - assets/images/dasarata.png
    - assets/images/profile-placeholder.jpeg
    - assets/lotties/login.json
    - assets/lotties/empty-state.json
    - assets/lotties/location-detail.json
    - assets/lotties/error-state.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
