name: CI - Build APK

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17.x'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    # - run: dart format --set-exit-if-changed .
    # - run: flutter analyze .
    - name: Create api-keys.xml
      run: |
        mkdir -p android/app/src/main/res/values/
        echo '<?xml version="1.0" encoding="utf-8"?>' > android/app/src/main/res/values/api-keys.xml
        echo '<resources>' >> android/app/src/main/res/values/api-keys.xml
        echo '    <string name="GoogleMapsKey">${{ secrets.GOOGLE_MAPS_API_KEY }}</string>' >> android/app/src/main/res/values/api-keys.xml
        echo '</resources>' >> android/app/src/main/res/values/api-keys.xml
    - name: Setup .env file
      run: |
        echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
        echo "BASE_URL_GOOGLE_MAPS=${{ secrets.BASE_URL_GOOGLE_MAPS }}" >> .env
        echo "GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> .env
    - name: Generate env.g.dart
      run: flutter pub run build_runner build --delete-conflicting-outputs
    - run: flutter build apk
    - uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk